Working prototype (very much WIP)

diff --git a/tudas b/tudas
--- a/tudas
+++ b/tudas
@@ -5,10 +5,13 @@ set -Eeuo pipefail
 
 function show_usage() {
     cat >&2 << EOF
-Usage: ${SCRIPT_NAME} [OPTION...]
-  -f, --file      
-  -v, --verbose   Display verbose messages
-  -h, --help      Show this help message then exit
+Usage: ${SCRIPT_NAME} [OPTION...] [GOAL_NAME]
+
+Options:
+  -f, --file          Choose a different file than the default (./Tudasfile)
+  -c, --compile-only  Don't run - just print the compiled script
+  -v, --verbose       Display verbose messages
+  -h, --help          Show this help message then exit
 EOF
 }
 
@@ -113,6 +116,7 @@ function cmd_is_installed() {
 }
 
 ARG_FILE=""
+ARG_GOAL=""
 
 function parse_commandline() {
 
@@ -134,6 +138,9 @@ function parse_commandline() {
                 ARG_FILE="${2}"
                 consume=2
             ;;
+            -c|--compile-only)
+                ARG_COMPILE_ONLY="true"
+            ;;
             -v|--verbose)
                 ARG_VERBOSE="true"
             ;;
@@ -141,9 +148,13 @@ function parse_commandline() {
                 ARG_HELP="true"
             ;;
             *)
-                log_error "Unrecognized argument: ${1}"
-                show_usage
-                exit 1
+                if [ "${ARG_GOAL}" = "" ]; then
+                    ARG_GOAL="${1}"
+                else
+                    log_error "Unrecognized argument: ${1}"
+                    show_usage
+                    exit 1
+                fi
             ;;
         esac
 
@@ -152,6 +163,10 @@ function parse_commandline() {
 
     if [ "${ARG_FILE}" = "" ]; then
         ARG_FILE="Tudasfile"
+    fi
+
+    if [ "${ARG_GOAL:-}" = "" ]; then
+        ARG_GOAL="default"
     fi
 }
 
@@ -191,9 +206,66 @@ for dep in "${DEPENDENCIES[@]}"; do
     cmd_is_installed "${dep}" || panic "Missing dependency \"${dep}\""
 done
 
+_current_goal=""
+_goals=()
+declare -A _goal_bodies
+declare -A _goal_dependencies
+declare -A _goal_reaches
+_prelude_body=()
+
+function new_goal() {
+    test "${#}" -eq 1 || panic "Expecting 1 argument: goal name"
+    local goal_name="${1}"
+    _current_goal="${goal_name}"
+    _goals+=("${goal_name}")
+    _goal_bodies["${goal_name}"]=""
+    _goal_dependencies["${goal_name}"]=""
+    _goal_reaches["${goal_name}"]=""
+}
+
 function process_line() {
     test "${#}" -eq 1 || panic "Expecting 1 argument: line contents"
     local line="${1}"
+
+    # Trim whitespace at begin and end of the line
+    if [[ "${line}" =~ ^[[:space:]]*(![[:space:]]+)[[:space:]]*$ ]]; then
+        line="${BASH_REMATCH[1]}"
+    fi
+
+    if [[ "${line}" =~ ^@goal(.*)$ ]]; then
+        local goal_name="${BASH_REMATCH[1]}"
+        if [[ "${goal_name}" =~ ^[[:space:]]+([a-zA-Z_\-]+)$ ]]; then
+            goal_name="${BASH_REMATCH[1]}"
+        else
+            log_error "Invalid goal name: ${goal_name}"
+            exit 1
+        fi
+        new_goal "${goal_name}"
+    elif [[ "${line}" =~ ^@depends_on[[:space:]]+(.*)$ ]]; then
+        # TODO: Throw error if no current goal
+        local dep_list="${BASH_REMATCH[1]}"
+        local existing_deps="${_goal_dependencies[${_current_goal}]}"
+        _goal_dependencies["${_current_goal}"]="${existing_deps} ${dep_list}"
+    elif [[ "${line}" =~ ^@reached_if[[:space:]]+(.*)[[:space:]]*$ ]]; then
+        # TODO: Throw error if no current goal
+        # TODO: Throw error if reach script is empty
+        local reach_script="${BASH_REMATCH[1]}"
+        _goal_reaches["${_current_goal}"]="${reach_script}"
+    elif [ "${_current_goal}" = "" ]; then
+        _prelude_body+=("${line}")
+    else
+        local current_body="${_goal_bodies["${_current_goal}"]}"
+        if [ "${current_body}" = "" ]; then
+            _goal_bodies["${_current_goal}"]="${line}"
+        else
+            _goal_bodies["${_current_goal}"]=$(cat << EOF
+${current_body}
+${line}
+EOF
+)
+        fi
+    fi
+
 }
 
 function process_file() {
@@ -205,8 +277,106 @@ function process_file() {
     done < "${file_path}"
 }
 
+function compile_script() {
+
+    cat << EOF
+#!/usr/bin/env bash
+${_prelude_body[@]}
+EOF
+
+    for goal_name in "${_goals[@]}"
+    do
+        compile_goal "${goal_name}"
+    done
+
+    if [ "${#_goals[@]}" -gt 0 ]; then
+        echo "\"__goal_${ARG_GOAL}\""
+    fi
+
+}
+
+function compile_goal() {
+    local goal_name="${1}"
+    local goal_body="${_goal_bodies[${goal_name}]}"
+    if [ "${goal_body}" = "" ]; then
+        goal_body="true"
+    fi
+
+    local dep_str="${_goal_dependencies[${goal_name}]}"
+    IFS=" " read -r -a dep_split <<< "$(echo "${dep_str}" | tr --squeeze-repeats "[:space:]")"
+
+    local dependencies=()
+    for dep in "${dep_split[@]}";
+    do
+        if [ "${dep}" != "" ]; then
+            dependencies+=("$(compile_dependency "${dep}")")
+        fi
+    done
+
+    if [ "${#dependencies[@]}" -eq 0 ]; then
+        dependencies=("true")
+    fi
+
+    # TODO: Validate dependencies
+
+    local reach_body="${_goal_reaches[${goal_name}]}"
+    if [ "${reach_body}" = "" ]; then
+        reach_body="false"
+    fi
+
+    cat << EOF
+__goal_${goal_name}_has_run=0
+__goal_${goal_name}() {
+    __goal_${goal_name}_has_run=1
+    __goal_${goal_name}_reached() {
+${reach_body}
+    }
+    __goal_${goal_name}_deps() {
+${dependencies[@]}
+    }
+    __goal_${goal_name}_body() {
+${goal_body[@]}
+    }
+    if __goal_${goal_name}_reached; then
+        echo "goal \"${goal_name}\": [already satisfied]"
+        return 0
+    fi
+    __goal_${goal_name}_deps || return 1
+    echo "goal \"${goal_name}\"..."
+    if (__goal_${goal_name}_body); then
+        echo "goal \"${goal_name}\": [success]"
+        return 0
+    else
+        result=\${?}
+        echo "goal \"${goal_name}\": [FAIL] (exit code \${result})"
+        exit \${result}
+    fi
+}
+EOF
+
+}
+
+function compile_dependency() {
+    local dep_name="${1}"
+    cat << EOF
+
+if [ "\${__goal_${dep_name}_has_run}" -eq 0 ]; then
+    "__goal_${dep_name}"
+fi
+EOF
+}
+
 function main() {
     process_file "${ARG_FILE}"
+    if [ "${ARG_COMPILE_ONLY:-}" = "true" ]; then
+        compile_script
+    else
+        if compile_script | bash -s; then
+            exit 0
+        else
+            exit ${?}
+        fi
+    fi
 }
 
 main
